apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  namespace: india
spec:
  replicas: 4
  selector:
    matchLabels:
     app: tomcat
  template:
    metadata:
     labels:
       app: tomcat
    spec:
     imagePullSecrets:
       - name: tgpasswd
     containers:
       - name: tomcat
         image:  vinodkumar8923/tomcat8:BUILD_NUMBER
         ports:
          - containerPort: 8080
      
